env:
  name: "develop"

http_listener:
  http:
    host: "0.0.0.0"
    port: "8081"
  https:
    host: "0.0.0.0"
    port: "8082"
  read_timeout: "10000"

shopify:
  https:
    host: <Shopify Store URL>
    port: <Shopify Store Port>
  response_timeout: "10000"
  admin_api:
    version: <Shopify Admin API version>
    access_token: <Shopify Admin API access token>

api:
  id: <API ID for autodiscovery>
  response_timeout: "10000"

