#%RAML 1.0
title: Shopify Order System API
description: System API for working with orders in Shopify.
mediaType: application/json

uses:
  OrderLibrary: modules/shopify-order-sapi-library.raml

/orders:
  displayName: Shopify orders
  description: Resource representing Shopify orders in standardized format.
  get:
    displayName: Retrieve a list of orders
    description: Retrieve a list of orders from Shopify.
    queryParameters:
      status?:
        description: Optional parameter for filtering orders by their status.
        type: string
        enum:
          - any
          - cancelled
          - closed
          - open
        default: open
        example: open
    responses:
      200:
        body:
          application/json:
            type: OrderLibrary.ShopifyOrders
  post:
    displayName: Create a Shopify order
    description: Creates a new order in Shopify.
    body:
      application/json:
        type: OrderLibrary.ShopifyOrder
    responses: 
      201:
        body: 
          application/json:
            type: !include modules/api-comprehensive-response.raml

  /{orderId}:
    displayName: Shopify specific order
    description: Resource representing a specific Shopify order in standardized format.
    uriParameters:
      orderId:
        type: string
        description: | 
          Globally unique identifier of an order. Shopify uses the order ID for API requests and
          responses. Shopify does not display the order id in its user interfaces. You can get the
          order ID via an API call (e.g., retrieve list of orders).
        example: "5294966145243"
          
    get:
      displayName: Retrieve a specific order
      description: Retrieve the order with the specified orderId from Shopify.
      responses:
        200:
          body:
            application/json:
              type: OrderLibrary.ShopifyOrder
